#!/usr/bin/env zsh
# 🧰 terminal-help — this tool, as a project: where it lives and how to install it.
# TH_TOPIC: terminal_help
# TH_EMOJI: 🧰
# TH_DESC:  terminal-help — the project: clone, install, upgrade, contribute

_th_help_terminal_help() {
    th_head "🧰" "terminal-help (the project)"
    th_text "This tool, as a project. A reference that loads with your"
    th_text "shell: zsh only, one line at startup, nothing host-specific"
    th_text "in the repository."
    th_row "Driving it:"      "get_terminal_help_usage"
    th_note "flags, writing your own topics, the file layout"

    th_sub "📍" "Where it lives"
    th_row "GitHub:"          "stonedog-code/terminal-help    (public)"
    th_row "Clone:"           "gh repo clone stonedog-code/terminal-help"
    th_row "npm:"             "NOT on npm — install from the clone"
    th_warn "npm i terminal-help is somebody else's package"
    th_note "an unrelated library for building help menus"

    th_sub "⚡" "Install and upgrade"
    th_row "Install:"         "./install.sh"
    th_note "asks which platforms, backs up your rc file, and"
    th_note "adds ONE marked block"
    th_row "Scripted:"        "./install.sh --targets linux --yes"
    th_row "Upgrade:"         "git pull && ./install.sh --yes"
    th_note "re-running IS the upgrade, and it keeps the topics"
    th_note "you already selected"
    th_row "Remove it:"       "./install.sh --uninstall"

    th_sub "🧱" "Dependencies"
    th_row "To use it:"       "zsh. Nothing else."
    th_row "To develop it:"   "uv  ·  docker (the bash 3.2 tier)"
    th_note "a missing tool is a FAILURE, not a skip"

    # Summary ends here. Everything below is the --detailed view.
    th_detail || return

    th_sub "🚦" "The gate — eight steps, all of them local"
    th_row "Parse:"           "bash scripts/check-syntax.sh"
    th_row "Startup:"         "bash scripts/test-user-file-loads.sh"
    th_row "macOS bash 3.2:"  "bash scripts/test-macos-bash.sh"
    th_note "runs the installer under real bash 3.2 in docker"
    th_row "Behaviour:"       "bash scripts/test-behaviour.sh"
    th_note "pytest driving a real zsh — nothing in tests/"
    th_note "tests Python"
    th_row "Docs:"            "bash scripts/check-docs-version.sh"
    th_warn "Four of the eight are --self-check runs that must FAIL"
    th_note "a guard only ever observed passing has not been"
    th_note "tested, it has been run; each self-check plants"
    th_note "the failure it exists to catch and confirms it is"
    th_note "caught BY NAME"

    th_sub "🔢" "Every PR bumps VERSION"
    th_row "Bump it:"         "bash scripts/set-version.sh 0.42.0"
    th_note "one bump per merged PR, no exceptions — it rides"
    th_note "in the line printed on every shell, so it is what"
    th_note "a person reads back when they say what they are"
    th_note "running, and a version covering three states of"
    th_note "the code identifies none of them"
    th_warn "Never hand-edit VERSION"
    th_note "the README quotes the banner VERSION feeds, and"
    th_note "editing one without the other is the DEFAULT"
    th_note "outcome, not a slip: the drift that produced once"
    th_note "ran 21 versions wide while every tier stayed"
    th_note "green. check-docs-version.sh is now that"
    th_note "comparison and gates the merge."

    th_sub "🧩" "Adding a topic to the package"
    th_row "One file:"        "help/<category>/<topic>.help.sh"
    th_note "the category is the directory name; nothing is"
    th_note "registered anywhere else, and the installer"
    th_note "discovers it"
    th_row "Header:"          "TH_TOPIC / TH_EMOJI / TH_DESC"
    th_note "get_<topic>_help is GENERATED from it — never"
    th_note "write the entry point or the _info twin by hand"
    th_row "The cut:"         "th_detail || return, in _th_help_<topic>"
    th_note "one body with a guard, never two bodies: it makes"
    th_note "the summary a prefix of the detail BY CONSTRUCTION"
    th_warn "The guard goes in the topic body, not in a TH_ALSO one"
    th_note "both placements hide the same text from the"
    th_note "summary, but the wrong one truncates only that"
    th_note "sub-section rather than the topic, and a"
    th_note "sub-function below it still prints"
    th_row "Cap:"             "40 lines at 80 columns, asserted per topic"

    th_sub "💡" "Quick tips"
    th_row "Develop live:"    "./install.sh --link"
    th_note "symlinks the clone instead of copying, so edits"
    th_note "are live. Only on a machine where the clone is"
    th_note "permanent — the normal install copies to"
    th_note "~/.terminal-help precisely so a ~/.zshrc never"
    th_note "names a path the next machine lacks."
    th_row "Contribute back:" "scripts/promote-extensions.sh"
    th_note "moves a topic you wrote in ~/.zshrc-help.d into"
    th_note "the repo"
    th_row "Nothing loading:" "th_doctor"
    th_row "Silence it:"      "TH_QUIET=1    (in ~/.zshenv)"
    th_note "that also skips user_on_load"
}
