#!/usr/bin/env bash
#
# promote-extensions.sh — collect your local help extensions into a report you
# can fold back into the package, so an addition you made for yourself can
# become a contribution.
#
#   scripts/promote-extensions.sh            # write PROMOTIONS.md
#   scripts/promote-extensions.sh --stdout   # print it instead
#
# IT DOES NOT EDIT ANY CODE, and that is deliberate. The obvious version of
# this script would find `_th_help_git() { ... }` in the package and splice the
# extension's body into it. Shell has no parser here: that means matching a
# closing brace with a regex, and it breaks on a nested function, a case
# statement, a brace inside a string, or `function f {` instead of `f() {`. A
# bad splice corrupts the topic for everyone who installs next. Producing a
# report a human folds in by hand is slower exactly once, and never wrong.

set -uo pipefail

TH_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
USER_HELP_DIR="${TH_USER_HELP_DIR:-${ZDOTDIR:-$HOME}/.zshrc-help.d}"
EXT_DIR="$USER_HELP_DIR/extensions"
OUT="$TH_DIR/PROMOTIONS.md"
TO_STDOUT=0
[ "${1:-}" = "--stdout" ] && TO_STDOUT=1

if [ ! -d "$EXT_DIR" ]; then
    echo "No extensions directory at $EXT_DIR — nothing to promote." >&2
    exit 0
fi

shopt -s nullglob
files=("$EXT_DIR"/*.help.sh)
if [ "${#files[@]}" -eq 0 ]; then
    echo "No *.help.sh in $EXT_DIR — nothing to promote." >&2
    exit 0
fi

# Where does the package keep the topic this extension extends?
base_file_for() {
    local topic="$1"
    find "$TH_DIR/help" -mindepth 2 -name '*.help.sh' -not -path '*/user/*' \
        -exec grep -l "^# TH_TOPIC:[[:space:]]*${topic}\$" {} + 2>/dev/null | head -n1
}

render() {
    echo "# Extensions to promote"
    echo
    echo "Generated by \`scripts/promote-extensions.sh\` from \`$EXT_DIR\`."
    echo "Nothing here has been applied — this is a worklist, not a patch."
    echo
    local f topic base extends
    for f in "${files[@]}"; do
        topic=$(basename "$f" .help.sh)
        # A file may extend a topic whose name differs from its filename.
        extends=$(grep -oE '^[[:space:]]*th_extend[[:space:]]+[a-z0-9_]+' "$f" | awk '{print $2}' | sort -u | tr '\n' ' ')
        [ -n "$extends" ] && topic="${extends%% *}"
        base=$(base_file_for "$topic")

        echo "## \`$topic\` — from \`${f/#$HOME/\~}\`"
        echo
        if [ -n "$base" ]; then
            echo "Base file: \`${base#$TH_DIR/}\`"
        else
            echo "**No base topic named \`$topic\` ships with the package.** This is a"
            echo "new topic rather than an extension — consider adding the file itself"
            echo "under \`help/technologies/\` (or the right category) with a TH_TOPIC header."
        fi
        echo
        echo "Checklist:"
        echo
        echo "- [ ] fold the rows below into the base topic, in the section where they belong"
        echo "- [ ] check nothing already says the same thing"
        echo "- [ ] make it generic — no hostnames, no internal paths, nothing about one machine"
        echo "- [ ] \`bash scripts/check-syntax.sh\`"
        echo "- [ ] branch, PR, and delete your local extension once it has merged"
        echo
        echo '```zsh'
        cat "$f"
        echo '```'
        echo
    done
    echo "---"
    echo
    echo "Remember the local file keeps working either way. Delete it only after"
    echo "the package version has merged, or you will see the same rows twice."
}

if [ "$TO_STDOUT" -eq 1 ]; then
    render
else
    render > "$OUT"
    echo "Wrote ${OUT#$TH_DIR/} — ${#files[@]} extension file(s)."
    echo "Review it, fold the rows into the base topics by hand, then open a PR."
fi
